### ISSUE TITLE
includeRegex fatally fails

### ISSUE THREAD

**Issue by filler** [piyush0101/jenkins-view-builder#12]
Hello!

It looks like that jobs which leverage `includeRegex` in their yaml fatally fail under `0.7.0`:

```
Updating view data in Jenkins
'regex'
make: *** [build-views] Error 1
```

The `make` target in question for the above is as follows:

```
build-views: jenkins-ship
  @$(SHELLPREP) && docker exec -it $(ID) jenkins-view-builder \
      update --conf /jjb/jenkins_jobs.ini \
      /jjb/views/
```

Ive found that subbing out `includeRegex` for `regex` in the yaml fixes this issue:

```
-    includeRegex: "^chef-.*$"
+    regex: "^chef-.*$"
```

We leveraged `includeRegex` in `0.5.0` without issue.  Perhaps the change at https://github.com/piyush0101/jenkins-view-builder/pull/9 broke this?

Again, much :sparkling_heart: for `jenkins-view-builder`!

![](http://gifs.joelglovier.com/thumbs-up/thumbs-up.gif)

**Comment by piyush0101** [comment]
Glad that you like jenkins-view-builder :)

Thanks for reporting this issue. I'll have a look at this today.

**Comment by piyush0101** [comment]
Does it happen with the list view?

**Comment by piyush0101** [comment]
Could you send the view yaml file you are using?

**Comment by amihura** [comment]
I can send the yaml, so
It doesn't work:
  -view:

```
  type: list
  name: test-view
  includeRegex: 'test-.*'
  columns:
    - status
    - weather
    - job
    - last_success
    - last_failure
    - last_duration
    - build_button
  recurse: False`
```

It works:

  `- view:

```
  type: list
  name: test-view
  regex: 'test-.*'
  columns:
    - status
    - weather
    - job
    - last_success
    - last_failure
    - last_duration
    - build_button
  recurse: False`
```

checked just for list view. Thanks.

**Comment by filler** [comment]
Hello!

My YAML looks like @amihura's wrt what works and what doesnt.  Heres full text however:

FAILS:

``` yaml
---
- view:
    type: list
    name: chef
    description: Chef jobs via jenkins-view-builder
    includeRegex: "^chef-.*$"
    columns:
    - status
    - weather
    - job
    - last_success
    - last_failure
    - last_duration
    - build_button
    recurse: False
```

SUCCEEDS:

``` yaml
---
- view:
    type: list
    name: chef
    description: Chef jobs via jenkins-view-builder
    regex: "^chef-.*$"
    columns:
    - status
    - weather
    - job
    - last_success
    - last_failure
    - last_duration
    - build_button
    recurse: False
```
