### ISSUE TITLE
cannot serialize regex

### ISSUE THREAD

**Issue by mark-casey** [piyush0101/jenkins-view-builder#3]
Please let me know if there is a better place for asking this. I didn't see any specific guidance but I may have missed it. :)

I am able to test and update a handful of view configs, but when I try to use the regex: tag in the YAML I get:

```
jenkins@mack:~$ jenkins-view-builder test jenkins_CUSTOM/jvb/faster.yml
cannot serialize {'regex': '.*-faster(-.*|$)'} (type dict)
jenkins@mack:~$
```

Some research on the Google seems to indicate this may be coming from eTree? I tried it in a straightforward way, and also tried to use an Anchor and Alias to see if I could change the evaluation order a bit and trick it into a happier codepath. Here are those:

**normal**

```
- view:
    type: list
    name: faster
    description: faster
    jobs:
     - regex: '.*-faster(-.*|$)'
    columns:
     - status
     - weather
     - build_button
     - job
     - last_duration
     - last_success
     - last_failure
    recurse: False
```

**attempt at being clever**

```
- view:
    regex: &regex_anchor { regex: '.*-faster(-.*|$)' }
    type: list
    name: faster
    description: faster
    jobs:
     - *regex_anchor
    columns:
     - status
     - weather
     - build_button
     - job
     - last_duration
     - last_success
     - last_failure
    recurse: False
```

I was wondering if anything jumps out at you in this, or what steps I might take next.

**Comment by piyush0101** [comment]
Can you try the following yaml. You can omit the `jobs` section all together and just include the  `includeRegex` flag. I do agree that its not very intuitive. We should have `regex` instead of an `includeRegex` flag. Please let me know how it goes.

```
- view:
    type: list
    name: faster
    description: faster
    includeRegex: '.*-faster(-.*|$)'
    columns:
     - status
     - weather
     - build_button
     - job
     - last_duration
     - last_success
     - last_failure
    recurse: False
```
